### ISSUE TITLE
no 2.2.0 tag?

### ISSUE THREAD

**Issue by whit537** [thieman/py-dag#13]
:-)

**Comment by whit537** [comment]
You've got 'em for earlier versions ...

**Comment by thieman** [comment]
Sorry, this was apparently a typo as there is an erroneous `0.2.0` tag which should have been `2.2.0`. I've pushed a new `2.2.0` tag and left the `0.2.0` there in case someone was actually using it. Sorry for the delay, I seem to have inadvertently turned off my notifications for this repo.
