### ISSUE TITLE
What is the graph = None arg?

### ISSUE THREAD

**Issue by qzmfranklin** [thieman/py-dag#17]
What is the point of using a class if you pass in the graph as a parameter anyways?

**Comment by thieman** [comment]
It's a flexibility thing. Without the optional `graph` arg, you perform stateful operations on the object. If you pass `graph` in manually, you can use the methods as if they're static methods.

**Comment by qzmfranklin** [comment]
Just saw you closed the issue.

Then just make it a staticmethod, then call the static method from the class method. Otherwise people cannot figure out the intention without actually understanding the source code. This is just defeating the point of using an API

**Comment by thieman** [comment]
Thanks for your input. This is a tiny library I built for myself; I'm happy other people somehow found it and are using it but I'm not going to contribute any direct maintenance unless it's something I personally need. And I, personally, can use it fine the way it is.

I encourage you to either submit a PR with your changes for review or fork the library. This library is available under the [MIT License](https://tldrlegal.com/license/mit-license) so you can do basically whatever you want with it. If you make a version significantly better than this one I will probably move over to using yours.

**Comment by thieman** [comment]
I've added a small note to the README to reflect this https://github.com/thieman/py-dag/commit/84d48353a58dcf7f6a17fab1e811346b25d0d481
